server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5436/user_db
    username: application
    password: "123456"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  jwt:
    # Matches API Gateway secret key
    secret: liverpoolvodich123456
    # 24 hours in milliseconds (86,400,000 ms)
    access-token-expiration-ms: 86400000
    # 7 days in milliseconds (604,800,000 ms)
    refresh-token-expiration-ms: 604800000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.coding: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
