-- V1__init_catalog_schema.sql
-- Enable UUID extension if supported
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 1. BRANDS
CREATE TABLE IF NOT EXISTS BRANDS (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    country VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_brands_name ON BRANDS (LOWER(name));

-- 2. CATEGORIES (Hierarchical: Parent-Child)
CREATE TABLE IF NOT EXISTS CATEGORIES (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    parent_id UUID,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES CATEGORIES (id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_categories_name ON CATEGORIES (LOWER(name));
CREATE INDEX IF NOT EXISTS idx_categories_parent_id ON CATEGORIES (parent_id);

-- 3. SUPPLIERS
CREATE TABLE IF NOT EXISTS SUPPLIERS (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_suppliers_name ON SUPPLIERS (LOWER(name));

-- 4. PRODUCT_GROUPS
CREATE TABLE IF NOT EXISTS PRODUCT_GROUPS (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_product_groups_name ON PRODUCT_GROUPS (LOWER(name));

-- 5. TAGS
CREATE TABLE IF NOT EXISTS TAGS (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tags_name ON TAGS (LOWER(name));

-- 6. PRODUCTS
CREATE TABLE IF NOT EXISTS PRODUCTS (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sku VARCHAR(255) NOT NULL,
    barcode VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    price NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    package_size NUMERIC(10, 3),
    unit_of_measure VARCHAR(20),
    category_id UUID,
    brand_id UUID,
    supplier_id UUID,
    group_id UUID,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT uq_products_barcode UNIQUE (barcode),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES CATEGORIES (id) ON DELETE SET NULL,
    CONSTRAINT fk_products_brand FOREIGN KEY (brand_id) REFERENCES BRANDS (id) ON DELETE SET NULL,
    CONSTRAINT fk_products_supplier FOREIGN KEY (supplier_id) REFERENCES SUPPLIERS (id) ON DELETE SET NULL,
    CONSTRAINT fk_products_group FOREIGN KEY (group_id) REFERENCES PRODUCT_GROUPS (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_products_category_id ON PRODUCTS (category_id);
CREATE INDEX IF NOT EXISTS idx_products_brand_id ON PRODUCTS (brand_id);
CREATE INDEX IF NOT EXISTS idx_products_supplier_id ON PRODUCTS (supplier_id);
CREATE INDEX IF NOT EXISTS idx_products_group_id ON PRODUCTS (group_id);

-- 7. PRODUCT_TAGS (Many-to-Many Join Table)
CREATE TABLE IF NOT EXISTS PRODUCT_TAGS (
    product_id UUID NOT NULL,
    tag_id UUID NOT NULL,
    PRIMARY KEY (product_id, tag_id),
    CONSTRAINT fk_product_tags_product FOREIGN KEY (product_id) REFERENCES PRODUCTS (id) ON DELETE CASCADE,
    CONSTRAINT fk_product_tags_tag FOREIGN KEY (tag_id) REFERENCES TAGS (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_product_tags_tag_id ON PRODUCT_TAGS (tag_id);

-- 8. PRODUCT_ATTRIBUTES (One-to-Many Attributes)
CREATE TABLE IF NOT EXISTS PRODUCT_ATTRIBUTES (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL,
    attr_key VARCHAR(255) NOT NULL,
    attr_value VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_attributes_product FOREIGN KEY (product_id) REFERENCES PRODUCTS (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_product_attributes_product_id ON PRODUCT_ATTRIBUTES (product_id);

-- 9. PRODUCT_IMAGES (ElementCollection)
CREATE TABLE IF NOT EXISTS PRODUCT_IMAGES (
    product_id UUID NOT NULL,
    image_url VARCHAR(1000) NOT NULL,
    CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES PRODUCTS (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON PRODUCT_IMAGES (product_id);
