server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    # A standalone server does not register with itself or fetch registry
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    root: INFO
    org.springframework.cloud: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
