version: "3.8"

services:
  postgres-catalog:
    image: postgres:16-alpine
    container_name: esupermarket-postgres-catalog-1
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: application
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: catalog_db
    volumes:
      - catalog_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U application -d catalog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-user:
    image: postgres:16-alpine
    container_name: esupermarket-postgres-user-1
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: application
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: user_db
    volumes:
      - user_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U application -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-order:
    image: postgres:16-alpine
    container_name: esupermarket-postgres-order-1
    restart: always
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: application
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: order_db
    volumes:
      - order_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U application -d order_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-inventory:
    image: postgres:16-alpine
    container_name: esupermarket-postgres-inventory-1
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: application
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: inventory_db
    volumes:
      - inventory_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U application -d inventory_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  catalog_pgdata:
    name: catalog_pgdata
  user_pgdata:
    name: user_pgdata
  order_pgdata:
    name: order_pgdata
  inventory_pgdata:
    name: inventory_pgdata

